#!/usr/bin/env bash

#: exec_target = cli

## Initialize/reinstall site
## Usage: fin init-site [--wcs]
## Parameters:
## --wcs Set default site email address

# Include helper functions
. $(dirname "$0")/helper-functions

## Settings
# PROJECT_ROOT and DOCROOT are set as env variables in cli
DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"

# Abort if anything fails
set -e

#-------------------------- Functions --------------------------------

# Prompt for user-supplied email address
check_email ()
{
  if [ -n "$source" ]; then
    if [ $source = "--wcs" ]; then
        email="wcs-drupal-site-admins@utlists.utexas.edu"
    fi
  fi
  if [ -z "$email" ]; then
    read -p "Enter email address for initial account: " user_supplied_email
    email=${user_supplied_email}
  fi
}

# Install site
site_install ()
{
  cd $DOCROOT_PATH
  # We disable email sending here so site-install does not return an error
  # Credit: https://www.drupal.org/project/phpconfig/issues/1826652#comment-12071700
  drush site-install utexas -y \
    install_configure_form.enable_update_status_module=NULL \
    --account-name="site-admin" \
    --site-name='UT Drupal Kit' \
    --site-mail="$email" \
    --account-mail="$email"
}

#-------------------------- END: Functions --------------------------------

#-------------------------- Execution --------------------------------

# Project initialization steps
echo "******** Install UT Drupal Kit ********"
source="$1"
check_email
time site_install
echo "PROJECT URL: http://${VIRTUAL_HOST}"
