#!/usr/bin/env bash

#: exec_target = cli

## Initialize/reinstall site
##
## Usage: fin init-site

# Include helper functions
. $(dirname "$0")/helper-functions

# Abort if anything fails
set -e

#-------------------------- Settings --------------------------------

# PROJECT_ROOT and DOCROOT are set as env variables in cli
SITE_DIRECTORY="default"
DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
SITEDIR_PATH="${DOCROOT_PATH}/sites/${SITE_DIRECTORY}"

#-------------------------- END: Settings --------------------------------

#-------------------------- Functions --------------------------------

# Fix file/folder permissions
fix_permissions ()
{
  echo "Making site directory writable..."
  chmod 755 "${SITEDIR_PATH}"
}

# Prompt for user-supplied email address
check_email ()
{
  if [ -n "$source" ]; then
    echo $source
    if [ $source = "--wcs" ]; then
        email="wcs-drupal-site-admins@utlists.utexas.edu"
    fi
  fi
  echo $email
  if [ -z "$email" ]; then
    read -p "Enter email address for initial account: " user_supplied_email
    email=${user_supplied_email} 
  fi
}

# Initialize local settings files
init_settings ()
{
  # Copy from settings templates
  copy_settings_file "${PROJECT_ROOT}/.docksal/drupal/default.settings.php" "${SITEDIR_PATH}/settings.php"
  copy_settings_file "${PROJECT_ROOT}/.docksal/drupal/default.settings.local.php" "${SITEDIR_PATH}/settings.local.php"
}

# Install site
site_install ()
{
  cd $DOCROOT_PATH
  # We disable email sending here so site-install does not return an error
  # Credit: https://www.drupal.org/project/phpconfig/issues/1826652#comment-12071700
  drush site-install utexas -y \
    install_configure_form.enable_update_status_module=NULL \
    --account-name="site-admin" \
    --site-name='UT Drupal Kit' \
    --site-mail="$email" \
    --account-mail="$email"
}

#-------------------------- END: Functions --------------------------------

#-------------------------- Execution --------------------------------

# Project initialization steps
echo "******** Install UT Drupal Kit ********"
source="$1"
check_email
fix_permissions
init_settings
time site_install
#-------------------------- END: Execution --------------------------------
