#!/usr/bin/env bash

## Initialize stack and site (full reset)
##
## Usage: fin init

# Include helper functions
. $(dirname "$0")/helper-functions

## Settings
# PROJECT_ROOT and DOCROOT are set as env variables in cli
SITE_DIRECTORY="default"
DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
SITEDIR_PATH="${DOCROOT_PATH}/sites/${SITE_DIRECTORY}"

# Initialize local settings files
init_settings ()
{
  # Copy from settings templates
  copy_settings_file "${PROJECT_ROOT}/.docksal/drupal/default.settings.php" "${SITEDIR_PATH}/settings.php"
  copy_settings_file "${PROJECT_ROOT}/.docksal/drupal/default.settings.local.php" "${SITEDIR_PATH}/settings.local.php"
}

# Fix file/folder permissions
fix_permissions ()
{
  echo "Making site directory writable..."
  chmod 755 "${SITEDIR_PATH}"
}

# Abort if anything fails
set -e

#-------------------------- Helper functions --------------------------------

# Console colors
red='\033[0;31m'
green='\033[0;32m'
green_bg='\033[42m'
yellow='\033[1;33m'
NC='\033[0m'

echo-red () { echo -e "${red}$1${NC}"; }
echo-green () { echo -e "${green}$1${NC}"; }
echo-green-bg () { echo -e "${green_bg}$1${NC}"; }
echo-yellow () { echo -e "${yellow}$1${NC}"; }

#-------------------------- Execution --------------------------------

# # Stack initialization
echo -e "${green_bg} Step 1 ${NC}${green} Initializing stack...${NC}"
if [[ $DOCKER_RUNNING == "true" ]]; then
	fin reset -f
else
	fin up
fi
echo "Waiting 10s for MySQL to initialize...";
sleep 10

echo    # move to a new line
echo -e "${green_bg} Step 2 ${NC}${green} Initializing VS Code configuration...${NC}"
create_dir "${PROJECT_ROOT}/.vscode"
# Copy over XDebug files
copy_settings_file "${PROJECT_ROOT}/.docksal/xdebug/launch.json" "${PROJECT_ROOT}/.vscode/launch.json"
# Copy over default VS Code settings
copy_settings_file "${PROJECT_ROOT}/.docksal/vscode/default.settings.json" "${PROJECT_ROOT}/.vscode/settings.json"
echo    # move to a new line

fix_permissions
init_settings

echo "Adding SSL support..."
fin addon install mkcert -g
fin mkcert create
fin system reset vhost-proxy

echo-green "Containers are up and refreshed, and VS Code is configured for settings and XDebug!";

#-------------------------- END: Execution --------------------------------
