#!/usr/bin/env bash

#: exec_target = cli

## Initialize/reinstall site
##
## Usage: fin init-site

# Include helper functions
. $(dirname "$0")/helper-functions

# Abort if anything fails
set -e

#-------------------------- Settings --------------------------------

# PROJECT_ROOT and DOCROOT are set as env variables in cli
SITE_DIRECTORY="default"
DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
SITEDIR_PATH="${DOCROOT_PATH}/sites/${SITE_DIRECTORY}"

#-------------------------- END: Settings --------------------------------

#-------------------------- Functions --------------------------------

# Fix file/folder permissions
fix_permissions ()
{
	echo "Making site directory writable..."
	chmod 755 "${SITEDIR_PATH}"
}

# Initialize local settings files
init_settings ()
{
	# Copy from settings templates
	copy_settings_file "${PROJECT_ROOT}/.docksal/drupal/default.settings.php" "${SITEDIR_PATH}/settings.php"
	copy_settings_file "${PROJECT_ROOT}/.docksal/drupal/default.settings.local.php" "${SITEDIR_PATH}/settings.local.php"
	# Create folder for simpletest snapshots
	create_dir "${PROJECT_ROOT}/${DOCROOT}/sites/simpletest"
	create_dir "${PROJECT_ROOT}/${DOCROOT}/sites/simpletest/browser_output"
}

# Install site
site_install ()
{
	cd $DOCROOT_PATH

	# We disable email sending here so site-install does not return an error
	# Credit: https://www.drupal.org/project/phpconfig/issues/1826652#comment-12071700
	drush site-install utexas -y \
		install_configure_form.enable_update_status_module=NULL \
		--site-name='Drupal Kit Rocks' \
		--site-mail="wcs-drupal-site-admins@utlists.utexas.edu" \
		--account-mail="wcs-drupal-site-admins@utlists.utexas.edu"

}

#-------------------------- END: Functions --------------------------------

#-------------------------- Execution --------------------------------

# Project initialization steps
fix_permissions
init_settings
time site_install
#-------------------------- END: Execution --------------------------------
