#!/usr/bin/env bash

# The 'paratest-js' command specifies which PHPUnit configuration defaults to use,
# to print verbose output, and to stop if there is a failure.
## fin test can be used with any available PHPUnit parameters

# fin paratest-js web/profiles/utexas/tests/src/FunctionalJavascript
# will run all tests found in the given directory

# fin paratest-js --filter=Office403Test
# will run test(s) with the class name "Office403Test"

# The following indicates that this command should be run within the docksal
# cli rather than the host. See https://docs.docksal.io/fin/custom-commands/#executing-commands-inside-cli
#: exec_target = cli

now="$(TZ='America/Chicago' date)"
echo "***********************************************************"
echo "Starting FunctionalJS tests on $now"
echo "If this fails immediately:"
echo "- Did you install the site?"
echo "- Have you run 'fin test-init'?"
echo "- Are you testing *FunctionalJS* tests?"
echo "If you get random failures, run the slower 'test-js'"
echo "***********************************************************"
/var/www/vendor/bin/paratest -p2 \
  --bootstrap /var/www/web/core/tests/bootstrap.php \
  -c /var/www/.docksal/drupal/testing/phpunit-js.xml \
  --testsuite=functional-javascript \
  --stop-on-failure \
  --stop-on-failure \
  --verbose=4 \
  $1
